version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: kpa_admin_2024
      MONGO_INITDB_DATABASE: kpa_production
    volumes:
      - mongodb_data:/data/db
    networks:
      - kpa-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:kpa_admin_2024@mongodb:27017/kpa_production?authSource=admin
      - DB_NAME=kpa_production
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-api-key-here}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - backend_models:/app/models
    networks:
      - kpa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8001/api}
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kpa-network

volumes:
  mongodb_data:
  backend_models:

networks:
  kpa-network:
    driver: bridge